#
# Setup and manage Python virtual environments that allow users to develop and
# test the OpenBT Python package.
#

[tox]
requires = tox>=4
env_list =

[testenv]
description = Run OpenBT's full test suite with or without coverage
passenv =
    COVERAGE_HTML
    COVERAGE_XML
    COVERAGE_FILE
setenv =
    COV_HTML = {env:COVERAGE_HTML:htmlcov}
    COV_XML  = {env:COVERAGE_XML:coverage.xml}
    COV_FILE = {env:COVERAGE_FILE:.coverage_openbt}
    DOC_ROOT = ../docs
deps =
    coverage: coverage
usedevelop =
    nocoverage: false
    coverage:   true
commands =
    nocoverage: pytest --pyargs openbt.tests
    coverage: coverage run --rcfile={toxinidir}/.coveragerc --data-file={env:COV_FILE} -m pytest ./src/openbt/tests

[testenv:report]
description = Generate XML and HTML format coverage reports
depends = coverage
deps = coverage
skip_install = true
commands = 
    coverage xml    --data-file={env:COV_FILE} -o {env:COV_XML}
    coverage html   --data-file={env:COV_FILE} -d {env:COV_HTML}
    coverage report --data-file={env:COV_FILE}

[testenv:check]
# The work done in this task does not alter any files.
description = Check code against typical Python standards
deps =
    setuptools
    flake8
commands =
    python setup.py check --strict --metadata
    flake8 --config={toxinidir}/.flake8

[testenv:html]
description = Generate OpenBT HTML-format documentation
usedevelop = true
deps =
    sphinx
    sphinxcontrib-bibtex
    sphinx_rtd_theme
    # Uncomment the following dependence if optional live-reloading will be used in this task
    #sphinx-autobuild
commands = 
    sphinx-build -W -E -b html {env:DOC_ROOT} {env:DOC_ROOT}/build_html
    # The command below is for live-reloading of the documentation during development. Uncomment it if you want to use it.
    #sphinx-autobuild -W -E -b html {env:DOC_ROOT} {env:DOC_ROOT}/build_html

[testenv:pdf]
description = Generate OpenBT PDF-format documentation
usedevelop = true
deps =
    sphinx
    sphinxcontrib-bibtex
allowlist_externals = make
commands = 
    sphinx-build -W -E -b latex {env:DOC_ROOT} {env:DOC_ROOT}/build_pdf
    make -C {env:DOC_ROOT}/build_pdf
