name: Test OpenBT Developer-mode Installation
env:
  CLONE_PATH: ${{ github.workspace }}
  PKG_ROOT:   ${{ github.workspace }}/openbt_pypkg
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  #####----- FULL TESTING WITHOUT COVERAGE
  # Mimic the way in which a developer might work including the direct use of
  # pytest.
  #
  # Since the sdist test action is installing MPI implementations manually using
  # OS package managers, we have this action install MPI via PyPI/pip.
  test_dev_mode:
    strategy:
      matrix:
        os: [macos-26, ubuntu-24.04]
        mpi_impl: ["openmpi", "mpich"]
    runs-on: ${{ matrix.os }}
    steps:
    ##-- Setup Testing Environment
    - name: Checkout OpenBT
      uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"
    - name: Setup Python dependencies
      run: $CLONE_PATH/.github/workflows/setup_base_python.sh ${{ runner.os }}
    - name: Install ${{ matrix.mpi_impl }}
      run: |
        if   [ "${{ matrix.mpi_impl }}" = "openmpi" ]; then
           python -m pip install openmpi
        elif [ "${{ matrix.mpi_impl }}" = "mpich" ]; then
           python -m pip install mpich
        else
           echo "Cannot install ${{ matrix.mpi_impl }}"
           exit 1
        fi
        python -m pip list
    ##-- Run full test suite
    - name: Run full OpenBT test suite
      run: |
        pushd $PKG_ROOT
        python -m pip install -v -e .
        popd
        ls -lart $PKG_ROOT/src/openbt
        ls -lart $PKG_ROOT/src/openbt/bin
        if   [ "${{ runner.os }}" = "Linux" ]; then
            ldd $PKG_ROOT/src/openbt/bin/openbtcli
        elif [ "${{ runner.os }}" = "macOS" ]; then
            otool -L $PKG_ROOT/src/openbt/bin/openbtcli
        fi
        pytest $PKG_ROOT/src/openbt/tests
