name: Test OpenBT in Anaconda
env:
  CLONE_PATH: ${{ github.workspace }}
  PKG_ROOT:   ${{ github.workspace }}/openbt_pypkg
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  #####----- FULL TESTING WITHOUT COVERAGE
  # Prefer full end-to-end test of local build/install rather than testing in
  # local clone alone.
  #
  # This also confirms that the test script is functional.
  test_anaconda:
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-26, macos-26-intel,
             ubuntu-22.04, ubuntu-24.04]
    runs-on: ${{ matrix.os }}

    steps:
    ##-- Setup Testing Environment
    # Following GH action messages, we explicitly remove the defaults channels
    # setting.  According to the setup-miniconda docs, this is related to a
    # workaround for
    #            https://github.com/conda/conda/issues/12356
    - uses: conda-incubator/setup-miniconda@v4.0.1
      with:
        miniconda-version: "latest"
        python-version: "3.14"
        auto-update-conda: true
        channels: conda-forge
        conda-remove-defaults: true
    - name: Checkout OpenBT
      uses: actions/checkout@v6
    - name: Setup miniconda & log
      shell: bash -el {0}
      run: |
        which python
        python --version
        conda info
        conda install pip
        conda list
    - name: Install prebuilt Open MPI via PyPI
      shell: bash -el {0}
      run: |
        python -m pip install openmpi
        conda list
        which mpicxx || echo "Cannot find the MPI installation"
        mpicxx -show || echo "Cannot check the MPI wrapper specification"

    ##-- Run full test suite
    - name: Run full OpenBT test suite
      shell: bash -el {0}
      run: |
        which python
        pushd $PKG_ROOT
        python -m pip install .
        popd
        $CLONE_PATH/tools/test_python_installation.py
